# Site settings
title: Leo Wong
email: gnowoel@gmail.com
description: Powered by Jekyll and hosted on Github Pages. Using default Jekyll theme.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gnowoel.com" # the base hostname & protocol for your site
twitter_username: gnowoel
github_username:  gnowoel

# Build settings
markdown: kramdown
