# Site settings
title: My blog
email: gnowoel@gmail.com
description: Learning to program and learning to write.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gnowoel.github.io" # the base hostname & protocol for your site
twitter_username: gnowoel
github_username:  gnowoel

# Build settings
markdown: kramdown
