hostname: "http://gnowoel.com" # e.g. http://example.com
basepath: "" # e.g. /blog

title: Leo Wong
email: gnowoel@gmail.com
description: An endeavor to build a static site generator for blogging.
twitter_username: gnowoel
github_username: gnowoel
